# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtype',
            name='department',
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='department',
            field=models.ManyToManyField(to='notifications.Department'),
        ),
    ]
