# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20170209_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
